/**
 * All user-facing Slovenian UI text lives here, grouped by surface — per
 * CLAUDE.md's language convention: code/comments/commits in English, UI text
 * in Slovenian, never mixed, never scattered inline.
 */
export const sl = {
  nav: {
    leads: "Stranke",
    pipeline: "Cevovod",
    analytics: "Analitika",
    settings: "Nastavitve",
    logout: "Odjava",
  },
  auth: {
    loginTitle: "Prijava",
    emailLabel: "E-poštni naslov",
    passwordLabel: "Geslo",
    loginButton: "Prijava",
    loginFailed: "Napačen e-poštni naslov ali geslo.",
    forgotPasswordLink: "Ste pozabili geslo?",
    registerTitle: "Ustvari račun",
    nameLabel: "Ime",
    registerButton: "Ustvari račun",
    inviteInvalid: "Povabilo ni veljavno ali je že bilo uporabljeno.",
    forgotPasswordTitle: "Pozabljeno geslo",
    forgotPasswordSubmit: "Pošlji povezavo za ponastavitev",
    forgotPasswordSent:
      "Če e-poštni naslov obstaja v našem sistemu, smo nanj poslali povezavo za ponastavitev gesla.",
    resetPasswordTitle: "Ponastavi geslo",
    resetPasswordSubmit: "Ponastavi geslo",
    resetPasswordInvalid: "Povezava za ponastavitev ni veljavna ali je potekla.",
    resetPasswordSuccess: "Geslo je bilo uspešno ponastavljeno. Prijavite se z novim geslom.",
  },
  leads: {
    title: "Stranke",
    empty: "Ni še nobene stranke.",
    filterAllStages: "Vse faze",
    filterAllSources: "Vsi viri",
    columnName: "Ime",
    columnEmail: "E-pošta",
    columnStage: "Faza",
    columnSource: "Vir",
    columnCreated: "Ustvarjeno",
    backToList: "Nazaj na seznam",
    contactInfo: "Kontaktni podatki",
    phoneLabel: "Telefon",
    answers: "Odgovori",
    noAnswers: "Ni odgovorov.",
    archivedAnswers: "Arhivirana vprašanja",
    archivedAnswersHint: "Ta vprašanja niso več del trenutne prijavne oblike, a odgovori so ohranjeni.",
    stageLabel: "Faza",
    stopSequence: "Ustavi e-sporočila",
    stopSequenceConfirm: "E-sporočila za to stranko so bila ustavljena.",
    unsubscribedNotice: "Ta stranka se je odjavila od e-sporočil.",
    addLead: "Dodaj stranko",
    editLead: "Uredi",
    saveLead: "Shrani",
    createSuccess: "Stranka je bila dodana.",
    updateSuccess: "Spremembe so bile shranjene.",
    duplicateEmail: "Stranka s tem e-poštnim naslovom že obstaja.",
    deleteLead: "Izbriši stranko",
    deleteLeadConfirmTitle: "Izbriši stranko?",
    deleteLeadConfirmBody:
      "Tega dejanja ni mogoče razveljaviti. Izbrisani bodo tudi vsi zapiski in načrtovana e-sporočila za to stranko.",
    cancelButton: "Prekliči",
    notesTitle: "Zapiski",
    notesEmpty: "Ni še zapiskov.",
    addNotePlaceholder: "Dodaj zapisek …",
    addNoteButton: "Dodaj",
    deleteNoteButton: "Izbriši",
  },
  pipeline: {
    title: "Cevovod",
  },
  analytics: {
    title: "Analitika",
    totalLeads: "Vse stranke",
    newThisWeek: "Novo ta teden",
    conversionRate: "Stopnja konverzije",
    medianDaysInStage: "Mediana dni v fazi",
    stuckCount: "Obtičale stranke",
    byStage: "Po fazah",
    bySource: "Po virih",
    noData: "Ni še podatkov.",
  },
  settings: {
    title: "Nastavitve",
    siteKeyTitle: "Vaš site key",
    siteKeyHint: "Ta ključ vstavite v obrazec na svoji spletni strani. Je javen — ne omogoča dostopa do vaših podatkov.",
    copyButton: "Kopiraj",
    copied: "Kopirano!",
    snippetTitle: "Primer zahteve",
    questionsTitle: "Vprašanja v prijavnem obrazcu",
    questionsHint:
      "Obstoječega ID-ja vprašanja ni mogoče spremeniti, ker bi to izgubilo povezavo s starimi odgovori. Lahko pa spremenite naslov, izbrišete vprašanje ali dodate novo.",
    addQuestion: "Dodaj vprašanje",
    questionIdLabel: "ID",
    questionLabelLabel: "Naslov",
    questionTypeLabel: "Tip",
    questionRequiredLabel: "Obvezno",
    questionOptionsLabel: "Možnosti (ločene z vejico)",
    deleteQuestion: "Izbriši",
    saveQuestions: "Shrani",
    savedSuccess: "Spremembe so bile shranjene.",
    typeText: "Besedilo",
    typeTextarea: "Daljše besedilo",
    typeSelect: "Izbira",
    typeCheckbox: "Potrditveno polje",
  },
  unsubscribe: {
    invalid: "Povezava za odjavo ni veljavna.",
    success: "Uspešno ste se odjavili od nadaljnjih e-sporočil.",
  },
  errors: {
    unexpected: "Prišlo je do nepričakovane napake. Poskusite znova.",
    validation: "Preverite vnesene podatke.",
    rateLimited: "Preveč poskusov. Poskusite znova kasneje.",
  },
} as const;
