/**
 * All user-facing Slovenian UI text lives here, grouped by surface — per
 * CLAUDE.md's language convention: code/comments/commits in English, UI text
 * in Slovenian, never mixed, never scattered inline.
 */
export const sl = {
  nav: {
    leads: "Stranke",
    pipeline: "Cevovod",
    applications: "Izpolnjene forme",
    emails: "Emaili",
    analytics: "Analitika",
    settings: "Nastavitve",
    logout: "Odjava",
  },
  auth: {
    loginTitle: "Prijava",
    emailLabel: "E-poštni naslov",
    passwordLabel: "Geslo",
    loginButton: "Prijava",
    loginFailed: "Napačen e-poštni naslov ali geslo.",
    forgotPasswordLink: "Ste pozabili geslo?",
    registerTitle: "Ustvari račun",
    nameLabel: "Ime",
    registerButton: "Ustvari račun",
    inviteInvalid: "Povabilo ni veljavno ali je že bilo uporabljeno.",
    forgotPasswordTitle: "Pozabljeno geslo",
    forgotPasswordSubmit: "Pošlji povezavo za ponastavitev",
    forgotPasswordSent:
      "Če e-poštni naslov obstaja v našem sistemu, smo nanj poslali povezavo za ponastavitev gesla.",
    resetPasswordTitle: "Ponastavi geslo",
    resetPasswordSubmit: "Ponastavi geslo",
    resetPasswordInvalid: "Povezava za ponastavitev ni veljavna ali je potekla.",
    resetPasswordSuccess: "Geslo je bilo uspešno ponastavljeno. Prijavite se z novim geslom.",
  },
  leads: {
    title: "Stranke",
    empty: "Ni še nobene stranke.",
    filterAllStages: "Vse faze",
    filterAllSources: "Vsi viri",
    columnName: "Ime",
    columnEmail: "E-pošta",
    columnStage: "Faza",
    columnSource: "Vir",
    columnCreated: "Ustvarjeno",
    backToList: "Nazaj na seznam",
    contactInfo: "Kontaktni podatki",
    phoneLabel: "Telefon",
    answers: "Odgovori",
    noAnswers: "Ni odgovorov.",
    archivedAnswers: "Arhivirana vprašanja",
    archivedAnswersHint: "Ta vprašanja niso več del trenutne prijavne oblike, a odgovori so ohranjeni.",
    stageLabel: "Faza",
    stopSequence: "Ustavi e-sporočila",
    stopSequenceConfirm: "E-sporočila za to stranko so bila ustavljena.",
    unsubscribedNotice: "Ta stranka se je odjavila od e-sporočil.",
    addLead: "Dodaj stranko",
    editLead: "Uredi",
    saveLead: "Shrani",
    createSuccess: "Stranka je bila dodana.",
    updateSuccess: "Spremembe so bile shranjene.",
    duplicateEmail: "Stranka s tem e-poštnim naslovom že obstaja.",
    deleteLead: "Izbriši stranko",
    deleteLeadConfirmTitle: "Izbriši stranko?",
    deleteLeadConfirmBody:
      "Tega dejanja ni mogoče razveljaviti. Izbrisani bodo tudi vsi zapiski in načrtovana e-sporočila za to stranko.",
    cancelButton: "Prekliči",
    notesTitle: "Zapiski",
    notesEmpty: "Ni še zapiskov.",
    addNotePlaceholder: "Dodaj zapisek …",
    addNoteButton: "Dodaj",
    deleteNoteButton: "Izbriši",
  },
  pipeline: {
    title: "Cevovod",
  },
  applications: {
    title: "Izpolnjene forme",
    empty: "Ni še nobene izpolnjene prijave.",
  },
  emails: {
    title: "Emaili",
    empty: "Ni še nobenega načrtovanega e-sporočila.",
    columnLead: "Stranka",
    columnStep: "Korak",
    columnStatus: "Status",
    columnScheduledFor: "Datum",
    cancelButton: "Prekliči",
    manageSequences: "Uredi sekvence",
    sequencesTitle: "Sekvence e-sporočil",
    sequencesEmpty: "Ni še nobene sekvence.",
    sequenceCreate: "Nova sekvenca",
    sequenceLimitReached: "Dosegli ste največje število sekvenc (5).",
    sequenceColumnName: "Ime",
    sequenceColumnTrigger: "Vir",
    sequenceColumnSteps: "Koraki",
    sequenceColumnStatus: "Status",
    sequenceStatusEnabled: "Aktivna",
    sequenceStatusDisabled: "Izklopljena",
    sequenceEnable: "Vklopi",
    sequenceDisable: "Izklopi",
    sequenceTriggerAnySource: "Vsi viri",
    sequenceDetailsTitle: "Osnovni podatki",
    sequenceNameLabel: "Ime sekvence",
    sequenceTriggerLabel: "Sproži ob prijavi z vira",
    sequenceTriggerTypeLabel: "Sekvenca se sproži",
    sequenceTriggerTypeLeadCreated: "Ob novi prijavi",
    sequenceTriggerTypeStageEntered: "Ob vstopu stranke v fazo",
    sequenceTriggerStageLabel: "Faza",
    sequenceEnabledLabel: "Sekvenca je aktivna",
    sequenceSave: "Shrani sekvenco",
    sequenceBackToList: "Nazaj na sekvence",
    sequenceNewTitle: "Nova sekvenca",
    sequenceEditTitle: "Uredi sekvenco",
    stepTitle: (n: number) => `Korak ${n}`,
    stepDayOffsetLabel: "Dan po prijavi",
    stepSubjectLabel: "Zadeva e-sporočila",
    stepBodyLabel: "Besedilo e-sporočila",
    stepConditionLabel: "Pošlji samo, če je stranka v eni od izbranih faz",
    stepConditionHint: "Če ne izberete nobene faze, se korak pošlje ne glede na fazo stranke.",
    stepMoveUp: "Gor",
    stepMoveDown: "Dol",
    stepDelete: "Izbriši korak",
    stepAdd: "Dodaj korak",
    editorBold: "Krepko",
    editorItalic: "Ležeče",
    editorLink: "Povezava",
    editorLinkPrompt: "Vnesite spletni naslov (https://...):",
    editorBulletList: "Seznam",
    editorOrderedList: "Oštevilčen seznam",
    editorInsertLeadName: "Ime stranke",
    editorInsertTrainerName: "Vaše ime",
    editorInsertButton: "Gumb",
    editorButtonLabelPrompt: "Napis na gumbu:",
    editorButtonHrefPrompt: "Spletni naslov gumba (https://...):",
    // Parameterized rather than assembled in JSX — see CLAUDE.md's UI-strings
    // convention: Slovenian sentence assembly belongs here, not in a component.
    applyToExisting: (n: number) => `Uporabi za obstoječe stranke (${n})`,
    applyConfirmTitle: "Uporabi spremembe za obstoječe stranke?",
    applyConfirmBody: (n: number) =>
      `To bo preklicalo še neposlana e-sporočila te sekvence za ${n} vključenih strank in jih znova razporedilo z zdajšnjo vsebino in koraki. Koraki, katerih nov datum bi bil že v preteklosti, ne bodo poslani z zamudo.`,
    applyConfirmButton: "Uporabi",
    applySuccess: (n: number) => `Sekvenca je bila znova uporabljena za ${n} strank.`,
    applyLimitExceeded: "Preveč vključenih strank naenkrat. Obrnite se na podporo.",
  },
  analytics: {
    title: "Analitika",
    totalLeads: "Vse stranke",
    newThisWeek: "Novo ta teden",
    conversionRate: "Stopnja konverzije",
    medianDaysInStage: "Mediana dni v fazi",
    stuckCount: "Obtičale stranke",
    byStage: "Po fazah",
    bySource: "Po virih",
    noData: "Ni še podatkov.",
  },
  settings: {
    title: "Nastavitve",
    siteKeyTitle: "Vaš site key",
    siteKeyHint: "Ta ključ vstavite v obrazec na svoji spletni strani. Je javen — ne omogoča dostopa do vaših podatkov.",
    copyButton: "Kopiraj",
    copied: "Kopirano!",
    snippetTitle: "Primer zahteve",
    questionsTitle: "Vprašanja v prijavnem obrazcu",
    questionsHint:
      "Obstoječega ID-ja vprašanja ni mogoče spremeniti, ker bi to izgubilo povezavo s starimi odgovori. Lahko pa spremenite naslov, izbrišete vprašanje ali dodate novo.",
    addQuestion: "Dodaj vprašanje",
    questionIdLabel: "ID",
    questionLabelLabel: "Naslov",
    questionTypeLabel: "Tip",
    questionRequiredLabel: "Obvezno",
    questionOptionsLabel: "Možnosti (ločene z vejico)",
    deleteQuestion: "Izbriši",
    saveQuestions: "Shrani",
    savedSuccess: "Spremembe so bile shranjene.",
    typeText: "Besedilo",
    typeTextarea: "Daljše besedilo",
    typeSelect: "Izbira",
    typeCheckbox: "Potrditveno polje",
  },
  unsubscribe: {
    invalid: "Povezava za odjavo ni veljavna.",
    success: "Uspešno ste se odjavili od nadaljnjih e-sporočil.",
  },
  errors: {
    unexpected: "Prišlo je do nepričakovane napake. Poskusite znova.",
    validation: "Preverite vnesene podatke.",
    rateLimited: "Preveč poskusov. Poskusite znova kasneje.",
  },
  admin: {
    title: "Trenerji",
    columnName: "Ime",
    columnEmail: "E-pošta",
    columnSiteKey: "Site key",
    columnFromEmail: "Pošiljatelj",
    columnStatus: "Status",
    columnCreated: "Ustvarjeno",
    statusActive: "Aktiven",
    statusDeactivated: "Deaktiviran",
    empty: "Ni še nobenega trenerja.",
    enterTrainer: "Vstopi",
    // Parameterized rather than assembled in JSX — see CLAUDE.md's UI-strings
    // convention: Slovenian sentence assembly belongs here, not in a component.
    viewingAs: (name: string) => `Ogleduješ kot ${name}`,
    exitImpersonation: "Izhod",
    setFromEmail: "Nastavi pošiljatelja",
    fromEmailPlaceholder: "Ime Priimek <ime@sub.domena.com>",
    fromEmailHint: "Domena mora biti že potrjena v Resendu, sicer pošiljanje ne bo delovalo.",
    fromEmailClear: "Počisti",
    fromEmailSave: "Shrani",
    fromEmailSaved: "Pošiljatelj je bil posodobljen.",
    inviteTitle: "Povabi trenerja",
    inviteEmailLabel: "E-poštni naslov",
    inviteSubmit: "Ustvari povabilo",
    inviteCreated: "Povabilo je bilo ustvarjeno.",
    inviteLinkLabel: "Povezava za registracijo",
    inviteSendFailed: "Povezava je ustvarjena, a e-sporočilo ni bilo poslano. Povezavo lahko trenerju posreduješ ročno.",
    deactivate: "Deaktiviraj",
    reactivate: "Ponovno aktiviraj",
    deactivateConfirmTitle: "Deaktiviraj trenerja?",
    deactivateConfirmBody:
      "Trener se ne bo mogel več prijaviti, vsa načrtovana e-sporočila pa bodo preklicana. Podatki ostanejo shranjeni in račun lahko kadar koli znova aktivirate.",
    reactivateConfirmTitle: "Ponovno aktiviraj trenerja?",
    reactivateConfirmBody: "Trener se bo spet lahko prijavil v svoj račun.",
  },
} as const;
